### ISSUE TITLE
Visonic Door/Window Sensor device handler issue

### ISSUE THREAD

**Issue by goyat11** [tomasaxerot/SmartThings#4]
hi i an using Visonic Door/Window Sensor handler for xfinity zigbee open close sensor its working fine but there is a problem with that, it drain battery so quick, may be in month can you please fix it. i will really appreciate ityou can reply me on goyat11@gmail.com

**Comment by tomasaxerot** [comment]
Hi Goyat, the sensor is nowadays natively supported by the smartthings hub, I recommend that you use that instead.  I will take down the handler I have.

**Comment by goyat11** [comment]
Hey thanks for replying. I really appreciate it. I did and its work fine
now.

On Mar 19, 2018 3:51 AM, "Tomas Axerot" <notifications@github.com> wrote:

Hi Goyat, the sensor is nowadays natively supported by the smartthings hub,
I recommend that you use that instead. I will take down the handler I have.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tomasaxerot/SmartThings/issues/4#issuecomment-374172160>,
or mute the thread
